[build-system]
requires = ["setuptools>=42", "wheel", "pybind11==2.11.1"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.cibuildwheel]
environment = "CFLAGS='-std=c++14'"
build = "cp3{7,8,9,10,11,12,13}-*"
