# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test for MLPerf inference submission checker using MLC script automation

on:
  pull_request:
    branches: [ "master_off", "dev_off" ]
    paths:
      - tools/submission/**
      - .github/workflows/test-submission-checker.yml
      - '!**.md'

env:
  PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.11", "3.12" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install mlcflow
        mlc pull repo mlcommons@mlperf-automations --branch=sub-gen-change
        git clone https://github.com/mlcommons/mlperf_inference_unofficial_submissions_v5.0 --depth 1
      # python3 -m pip install mlc-scripts
    - name: Test MLPerf inference submission checker
      run: |
        mlcr run,mlperf,inference,submission,checker --adr.inference-src.tags=_branch.submission_dir --adr.inference-src.version=custom --input=`pwd`/mlperf_inference_unofficial_submissions_v5.0 --src_version=v5.0 --extra_args=" --skip-extra-files-in-root-check --skip-extra-accuracy-files-check --skip-all-systems-have-results-check --skip-calibration-check" --quiet 
